/**
 * @haverstack/eleventy — `eject`
 * -------------------------------------------------------
 * Writes a starter `haverstack-base` layout into the site's `_includes`
 * so the whole build can flow through an editable Eleventy layout. The
 * build never writes here — ejecting is a deliberate one-off.
 */

import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve as resolvePath } from 'node:path';

export interface EjectableTemplate {
  filename: string;
  contents: string;
}

const HAVERSTACK_BASE = `{#
  haverstack-base — a starting point, generated by \`haverstack-eleventy eject\`.
  Turn it on with \`templates: { base: 'haverstack-base' }\` in the plugin
  options, then edit it however you like.

  Data on every page: content, title, record, meta, url, canonical, body
  (rendered HTML), bodyRaw (markdown, image links resolved), and on listing
  pages, collection. Globals: haverstack.site / .sites / .owner / .pages /
  .menus / .collections.
#}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% if title %}{{ title }} · {% endif %}{{ haverstack.site.content.title }}</title>
    {% if haverstack.site.content.description %}
    <meta name="description" content="{{ haverstack.site.content.description }}" />
    {% endif %}
    {% if canonical %}<link rel="canonical" href="{{ canonical }}" />{% endif %}
  </head>
  <body>
    <header>
      <a href="/">{{ haverstack.site.content.title }}</a>
      {%- set topNav = haverstack.menus["top-nav"] %}
      {%- if topNav %}
      <nav>
        {%- for item in topNav.items %}
        <a href="{{ item.url }}"{% if item.rel %} rel="{{ item.rel }}"{% endif %}>{{ item.label }}</a>
        {%- endfor %}
      </nav>
      {%- endif %}
    </header>

    <main>
      {{ content | safe }}
      {%- if collection %}
      <ul>
        {%- for m in collection.members %}
        <li>
          <a href="{{ m.url }}">{{ m.record.content.title or m.record.content.caption or m.record.id }}</a>
        </li>
        {%- endfor %}
      </ul>
      {%- endif %}
    </main>

    <footer>
      {%- set social = haverstack.menus.social %}
      {%- if social %}{% for item in social.items %}<a href="{{ item.url }}" rel="{{ item.rel }}">{{ item.label }}</a> {% endfor %}{% endif %}
      {%- if haverstack.owner %}<p>© {{ haverstack.owner.content.name }}</p>{% endif %}
    </footer>
  </body>
</html>
`;

export const EJECTABLE_TEMPLATES: EjectableTemplate[] = [
  { filename: 'haverstack-base.njk', contents: HAVERSTACK_BASE },
];

export interface EjectResult {
  written: string[];
  skipped: string[];
}

/** Write each ejectable template into `includesDir`, skipping existing files unless `force`. */
export async function runEject(
  includesDir: string,
  opts: { force?: boolean } = {},
): Promise<EjectResult> {
  const dir = resolvePath(process.cwd(), includesDir);
  await mkdir(dir, { recursive: true });

  const written: string[] = [];
  const skipped: string[] = [];
  for (const template of EJECTABLE_TEMPLATES) {
    const dest = join(dir, template.filename);
    if (existsSync(dest) && !opts.force) {
      skipped.push(template.filename);
      continue;
    }
    await writeFile(dest, template.contents);
    written.push(template.filename);
  }
  return { written, skipped };
}

export function formatEjectResult(result: EjectResult, includesDir: string): string {
  const lines: string[] = [];
  for (const name of result.written) lines.push(`  wrote    ${includesDir}/${name}`);
  for (const name of result.skipped)
    lines.push(`  skipped  ${includesDir}/${name} (exists — pass --force to overwrite)`);
  if (result.written.length > 0) {
    lines.push('');
    lines.push("Set `templates: { base: 'haverstack-base' }` in the plugin options to use it.");
  }
  return lines.join('\n');
}
